### ISSUE TITLE
Server address validation fails when using newer TLDs

### ISSUE THREAD

**Issue by circuit-breaker** [jp-bennett/Fwknop2#32]
Entering a hostname that has a newer TLD in it's domain name will generate an error & won't let you save your configuration. For example: foo.digital fails, foo.com is OK.

Looks like the version of org.apache.commons.validator.routines.DomainValidator being used pre-dates this revision: https://svn.apache.org/viewvc?view=revision&revision=1712699

**Comment by oneru** [comment]
Thanks for the report.  As quickly as new TLDs are popping up, I am very tempted to stop using the Apache validator, and simply check for an appropriately formatted hostname.  Either way, I'll make sure to fix this for the next beta, and it'll be ready for the next official release.

**Comment by jp-bennett** [comment]
I believe the latest release, 1.2.3, fixes this issue.  Please re-open if it's still a problem for you.
