### ISSUE TITLE
Camera fails to capture QR code on Galaxy S7 Edge

### ISSUE THREAD

**Issue by rugolt** [jp-bennett/Fwknop2#35]
Error "There is a problem with Android camera" appears.

**Comment by jp-bennett** [comment]
Are you on the beta channel?  This sounds like a permissions problem I ran into, should be fixed in the next relelease, coming in a couple weeks.

**Comment by rugolt** [comment]
Re: [jp-bennett/Fwknop2] Camera fails to capture QR code on Galaxy S7 Edge (#35)


No, I am not on the beta channel.
I used the regular version from F-Droid.






Are you on the beta channel? This sounds like a permissions problem I ran into, should be fixed in the next relelease, coming in a couple weeks.

**Comment by languitar** [comment]
Same thing with f-droid version on Nexus 5.

**Comment by jp-bennett** [comment]
I just released a point release that should correct this issue.  Once F-droid updates, it should work as expected.  It may take several days for F-droid to build and push the latest update.

**Comment by jp-bennett** [comment]
Closing as this should be fixed.
