### ISSUE TITLE
"Fwknop2 isn't responding" message with version 1.2.2 if firewall timeout is not configured

### ISSUE THREAD

**Issue by quincunx** [jp-bennett/Fwknop2#37]
As the firewall timeout is set in the server config, I've left this parameter empty in the Fwknop2 profile. But with the new version 1.2.2, which wants to show timeout notification after a successful knock, the app freezes and a "Fwknop2 isn't responding" is shown. If I set a timeout or disable the timeout notification in the settings, it works.

**Comment by jp-bennett** [comment]
You are absolutely correct, I can replicate that on my device.  The fix you suggest looks correct.  If you want to open a PR, I'll accept it.  Thanks!

**Comment by jp-bennett** [comment]
Looks good, I'll upload a new build shortly.
