### ISSUE TITLE
Send Knock error: "Failure generating SPA data" when multiple ports specified

### ISSUE THREAD

**Issue by waitfor1t** [jp-bennett/Fwknop2#53]
I keep getting this error "Failure generating SPA data", despite having what appears to be a valid config with multiple ports.  It would be really nice to have a log file to look at.  One port seems to work. I've tried multiple delimeters, though I think the correct syntax is "udp/500, udp/4500" (ie: comma delimeter). I tried looking at the code but I'm not a programmer so I got lost following what happens to access_str in SendSPA.java (This is where the error is).

**Comment by waitfor1t** [comment]
So it appears removing spaces works. Apologies - I did not test the string without spaces. The example configurations I have show spaces in the string between the protocols. So: "udp/500,udp/4500" works, but ""udp/500, udp/4500" does not work. [small rant]You know... trim() is pretty much in every language.. :) [/rant]

**Comment by jp-bennett** [comment]
Yep, I'll add the sanity check to remove any extra spaces.  Thanks for the catch.
