### ISSUE TITLE
OpenWRT fwknockd does not register knock, app says OK

### ISSUE THREAD

**Issue by Strykar** [jp-bennett/Fwknop2#57]
I'm trying to open port 8000 and port forward the connection to an Icecast HTTP server on the LAN behind the OpenWRT router. The Android app says OK when I knock but the OpenWRT fwknockd logs nothing. I've tried with and without GPG.
```
OpenWrt 18.06.2 Linux apu 4.14.95 #0 SMP Mon Jan 28 08:54:32 2019 x86_64 GNU/Linux
fwknopd server version 2.6.9
luci-app-fwknopd version git-19.051.55698-76cf653-1
```

```
Android 7.0 kernel-3.10.84
Cipherdyne fwknop2 - Last updated Oct 2017
```
![fwknop1](https://user-images.githubusercontent.com/2946372/54362344-c66f6400-468e-11e9-9854-e20a89a6ac05.png)
![fwknop2](https://user-images.githubusercontent.com/2946372/54362358-ccfddb80-468e-11e9-9af1-f600a80e3056.png)

OpenWRT conf -
```
root@openwrt:~# cat /var/etc/access.conf 
SOURCE ANY
keytype Base 64 key
hkeytype Base 64 key
snipped=
HMAC_KEY_BASE64 snipped==
FW_ACCESS_TIMEOUT 30

root@openwrt:~# cat /etc/fwknop/access.conf 
GPG_REMOTE_ID         <snipped>
SOURCE              ANY
KEY_BASE64          snipped=
HMAC_KEY_BASE64     snipped==
SOURCE: ANY;
DATA_COLLECT_MODE: PCAP;
GPG_REMOTE_ID: snipped;
GPG_DECRYPT_ID: snipped
GPG_HOME_DIR: /root/.gnupg;
FW_ACCESS_TIMEOUT: 60;
```

OpenWRT log does not register the knock - 
```
Thu Mar 14 19:03:46 2019 daemon.err fwknopd[13030]: [*] Ignoring unknown access parameter: 'keytype' in /var/etc/access.conf
Thu Mar 14 19:03:46 2019 daemon.err fwknopd[13030]: [*] Ignoring unknown access parameter: 'hkeytype' in /var/etc/access.conf
Thu Mar 14 19:03:46 2019 daemon.info fwknopd[13030]: Warning: REQUIRE_SOURCE_ADDRESS not enabled for access stanza source: 'ANY'
Thu Mar 14 19:03:46 2019 daemon.info fwknopd[13030]: Starting fwknopd
Thu Mar 14 19:03:46 2019 daemon.info fwknopd[13030]: Added jump rule from chain: INPUT to chain: FWKNOP_INPUT
Thu Mar 14 19:03:46 2019 daemon.info fwknopd[13030]: Added jump rule from chain: FORWARD to chain: FWKNOP_FORWARD
Thu Mar 14 19:03:46 2019 daemon.info fwknopd[13030]: Added jump rule from chain: PREROUTING to chain: FWKNOP_PREROUTING
Thu Mar 14 19:03:46 2019 daemon.info fwknopd[13030]: iptables 'comment' match is available
Thu Mar 14 19:03:46 2019 daemon.info fwknopd[13030]: Sniffing interface: eth0
Thu Mar 14 19:03:46 2019 daemon.info fwknopd[13030]: PCAP filter is: 'udp port 62201'
Thu Mar 14 19:03:46 2019 daemon.info fwknopd[13030]: Starting fwknopd main event loop.
```

What am I missing here?

**Comment by jp-bennett** [comment]
@Strykar Can you confirm that eth0 is actually the correct interface on the OpenWRT device?

It's possible that one of the networks is filtering the UDP packets, some corporate networks are known for policies like that.

You could try using the IP address instead of the url in the Android app, to rule out DNS issues.

**Comment by Strykar** [comment]
@jp-bennett `pppoe-wan` runs on the `eth0` interface, and the OpenWRT hint text for `PCAP_INTF` says `Specify the ethernet interface on which fwknopd will sniff packets.` Perhaps this could be worded differently? This threw me off, it works when I set the interface to `pppoe-wan`. Cheers!

One more Q, while it opens the port and port forwards fine, it closes the port again pretty quick, how can I keep the connection open for the Android client for as long as it needs?

**Comment by jp-bennett** [comment]
Hey, glad you got it working! The next version of the Android app has an option to automatically resend knocks. I need to do a new stable release soon, too.
