### ISSUE TITLE
App gone from Google Play store?

### ISSUE THREAD

**Issue by franzinc** [jp-bennett/Fwknop2#63]
Any chance of it coming back? Or is there another user-friendly, non-technical way to obtain it?

**Comment by jp-bennett** [comment]
It's on f-droid. I think I figured out why Google pulled it, hopefully all that was required was giving it a target age.

**Comment by jp-bennett** [comment]
@franzinc can you confirm that it's back?

**Comment by solhuebner** [comment]
I can see it on the playstore :)

**Comment by jp-bennett** [comment]
Awesome, thanks!
